name: flicktok_server
channels:
  - conda-forge
dependencies:
  - python=3.11
  - liblsl
  - black
  - flake8
  - fastapi
  - python-dotenv
  - uvicorn
  - python-socketio
  - pyyaml
  - rich
  - numpy
  # - pylsl=1.16.2
  # - bci-essentials=0.1.3
